import type {
  Message,
  Resource,
  ServiceDefinition,
  StudentProfile,
  SupportRequest,
  TeamMember,
} from "@/types";

export const services: ServiceDefinition[] = [
  {
    slug: "tutoring",
    name: "Academic Support",
    short: "Tutoring, study assistance and academic guidance.",
    description:
      "One-to-one tutoring and study coaching that helps you actually understand the material — concepts explained, worked examples, and revision plans built around your course.",
    icon: "GraduationCap",
    includes: ["Concept tutoring", "Exam revision plans", "Study coaching", "Course Q&A sessions"],
  },
  {
    slug: "technical-support",
    name: "Technical Support",
    short: "Software installation, configuration and troubleshooting.",
    description:
      "Get your tools working. Installation, environment setup, licensing, drivers and troubleshooting for the software your programme depends on.",
    icon: "Wrench",
    includes: ["Software installation", "Dev environment setup", "Troubleshooting", "Device & tool configuration"],
  },
  {
    slug: "programming",
    name: "Programming",
    short: "Debugging, development guidance and technical assistance.",
    description:
      "Pair-style debugging and development guidance. We walk through the error, explain the fix and help you build the skill, not just the file.",
    icon: "Code2",
    includes: ["Debugging sessions", "Code reviews", "Architecture guidance", "Language & framework coaching"],
  },
  {
    slug: "project-support",
    name: "Project Support",
    short: "Planning, architecture and implementation guidance.",
    description:
      "Support across the full project lifecycle — scoping, architecture, milestones, implementation guidance and documentation structure for coursework and final-year projects.",
    icon: "Layers",
    includes: ["Project scoping", "Architecture reviews", "Milestone planning", "Implementation guidance"],
  },
  {
    slug: "research-support",
    name: "Research Support",
    short: "Research direction, methodology and academic guidance.",
    description:
      "Guidance on framing research questions, choosing methodology, finding credible sources and structuring your analysis with academic rigour.",
    icon: "Microscope",
    includes: ["Topic framing", "Methodology guidance", "Literature navigation", "Analysis structuring"],
  },
  {
    slug: "documentation",
    name: "Documentation",
    short: "Proofreading, formatting and documentation assistance.",
    description:
      "Proofreading, referencing and formatting support so your own work reads clearly and meets your department's submission standards.",
    icon: "FileText",
    includes: ["Proofreading", "Referencing & citations", "Formatting to spec", "Technical documentation"],
  },
];

export const team: TeamMember[] = [
  {
    id: "t1",
    name: "Kwame Mensah",
    role: "Senior Engineer",
    specialization: "Full-stack · Debugging",
    availability: "AVAILABLE",
    activeRequests: 3,
    completedRequests: 62,
    rating: 4.9,
    initials: "KM",
  },
  {
    id: "t2",
    name: "Ama Boateng",
    role: "Academic Tutor",
    specialization: "Mathematics · Statistics",
    availability: "BUSY",
    activeRequests: 5,
    completedRequests: 88,
    rating: 4.8,
    initials: "AB",
  },
  {
    id: "t3",
    name: "Yaw Owusu",
    role: "Research Advisor",
    specialization: "Methodology · Data analysis",
    availability: "AVAILABLE",
    activeRequests: 2,
    completedRequests: 41,
    rating: 4.7,
    initials: "YO",
  },
  {
    id: "t4",
    name: "Efua Danso",
    role: "Technical Specialist",
    specialization: "Systems · Tooling",
    availability: "OFFLINE",
    activeRequests: 0,
    completedRequests: 35,
    rating: 4.6,
    initials: "ED",
  },
];

export const student: StudentProfile = {
  id: "s1",
  fullName: "Alex Nyarko",
  email: "alex.nyarko@student.edu.gh",
  phone: "+233 24 000 1122",
  university: "Kwame Nkrumah University of Science and Technology",
  department: "Computer Engineering",
  level: "400",
  studentId: "CE/2022/1183",
  initials: "AN",
};

export const requests: SupportRequest[] = [
  {
    id: "1",
    reference: "REQ-10482",
    title: "Website development project guidance",
    category: "project-support",
    description:
      "I'm building a departmental portal for my final-year project and need guidance on the architecture, database design and deployment approach. I have a partial React frontend already.",
    course: "CE 492 — Final Year Project",
    department: "Computer Engineering",
    technology: "React, Node.js, PostgreSQL",
    status: "IN_PROGRESS",
    priority: "HIGH",
    deadline: "2026-09-28T17:00:00Z",
    progress: 62,
    assignee: team[0],
    studentName: "Alex Nyarko",
    studentId: "CE/2022/1183",
    createdAt: "2026-09-08T09:12:00Z",
    updatedAt: "2026-09-13T14:05:00Z",
    files: [
      { id: "f1", name: "project-brief.pdf", size: 482_113, type: "application/pdf" },
      { id: "f2", name: "frontend-src.zip", size: 2_913_221, type: "application/zip" },
    ],
    quote: {
      id: "q1",
      summary: "Website Development Support",
      deliveryEstimate: "3–5 days",
      serviceAmount: 450,
      discount: 50,
      total: 400,
      currency: "GH₵",
      status: "ACCEPTED",
    },
    paymentStatus: "PAID",
    deliverables: [{ id: "d1", name: "architecture-review.pdf", size: 331_002, type: "application/pdf" }],
    history: [
      { status: "SUBMITTED", at: "2026-09-08T09:12:00Z" },
      { status: "UNDER_REVIEW", at: "2026-09-08T11:40:00Z" },
      { status: "QUOTED", at: "2026-09-09T08:02:00Z", note: "Quote issued: GH₵ 400" },
      { status: "PAID", at: "2026-09-09T16:20:00Z" },
      { status: "ASSIGNED", at: "2026-09-10T08:00:00Z", note: "Assigned to Kwame Mensah" },
      { status: "IN_PROGRESS", at: "2026-09-10T10:15:00Z" },
    ],
  },
  {
    id: "2",
    reference: "REQ-10476",
    title: "Debugging a Python data pipeline",
    category: "programming",
    description:
      "My pandas pipeline throws a merge error on large CSVs and I can't trace where the index breaks. I'd like to understand the cause, not just a patch.",
    course: "CE 415 — Data Engineering",
    department: "Computer Engineering",
    technology: "Python, pandas",
    status: "UNDER_REVIEW",
    priority: "NORMAL",
    deadline: "2026-09-22T12:00:00Z",
    progress: 15,
    studentName: "Alex Nyarko",
    studentId: "CE/2022/1183",
    createdAt: "2026-09-12T18:45:00Z",
    updatedAt: "2026-09-13T07:30:00Z",
    files: [{ id: "f3", name: "pipeline.py", size: 18_221, type: "text/x-python" }],
    paymentStatus: "UNPAID",
    deliverables: [],
    history: [
      { status: "SUBMITTED", at: "2026-09-12T18:45:00Z" },
      { status: "UNDER_REVIEW", at: "2026-09-13T07:30:00Z" },
    ],
  },
  {
    id: "3",
    reference: "REQ-10461",
    title: "MATLAB installation and licence setup",
    category: "technical-support",
    description: "MATLAB fails to activate on my laptop after the university licence renewal.",
    department: "Computer Engineering",
    status: "COMPLETED",
    priority: "LOW",
    deadline: "2026-09-05T09:00:00Z",
    progress: 100,
    assignee: team[3],
    studentName: "Alex Nyarko",
    studentId: "CE/2022/1183",
    createdAt: "2026-09-02T10:00:00Z",
    updatedAt: "2026-09-05T08:10:00Z",
    files: [],
    quote: {
      id: "q2",
      summary: "Technical Support Session",
      deliveryEstimate: "1 day",
      serviceAmount: 120,
      discount: 0,
      total: 120,
      currency: "GH₵",
      status: "ACCEPTED",
    },
    paymentStatus: "PAID",
    deliverables: [{ id: "d2", name: "setup-notes.pdf", size: 92_110, type: "application/pdf" }],
    history: [
      { status: "SUBMITTED", at: "2026-09-02T10:00:00Z" },
      { status: "PAID", at: "2026-09-03T09:00:00Z" },
      { status: "COMPLETED", at: "2026-09-05T08:10:00Z" },
    ],
  },
  {
    id: "4",
    reference: "REQ-10455",
    title: "Research methodology review for IoT study",
    category: "research-support",
    description: "Need guidance on selecting a mixed-methods approach for an IoT adoption study.",
    course: "CE 480 — Research Methods",
    department: "Computer Engineering",
    status: "AWAITING_PAYMENT",
    priority: "URGENT",
    deadline: "2026-09-19T23:59:00Z",
    progress: 30,
    assignee: team[2],
    studentName: "Alex Nyarko",
    studentId: "CE/2022/1183",
    createdAt: "2026-09-11T13:20:00Z",
    updatedAt: "2026-09-13T09:00:00Z",
    files: [{ id: "f4", name: "proposal-draft.docx", size: 221_882, type: "application/msword" }],
    quote: {
      id: "q3",
      summary: "Research Methodology Guidance",
      deliveryEstimate: "2–3 days",
      serviceAmount: 280,
      discount: 30,
      total: 250,
      currency: "GH₵",
      status: "PENDING",
    },
    paymentStatus: "AWAITING",
    deliverables: [],
    history: [
      { status: "SUBMITTED", at: "2026-09-11T13:20:00Z" },
      { status: "UNDER_REVIEW", at: "2026-09-11T15:00:00Z" },
      { status: "QUOTED", at: "2026-09-12T10:05:00Z" },
      { status: "AWAITING_PAYMENT", at: "2026-09-13T09:00:00Z" },
    ],
  },
  {
    id: "5",
    reference: "REQ-10440",
    title: "Proofreading for thesis chapter three",
    category: "documentation",
    description: "Formatting and referencing pass on chapter three, APA 7th edition.",
    department: "Biomedical Engineering",
    status: "SUBMITTED",
    priority: "NORMAL",
    deadline: "2026-09-25T17:00:00Z",
    progress: 5,
    studentName: "Naa Adjeley",
    studentId: "BM/2021/0442",
    createdAt: "2026-09-13T08:00:00Z",
    updatedAt: "2026-09-13T08:00:00Z",
    files: [],
    paymentStatus: "UNPAID",
    deliverables: [],
    history: [{ status: "SUBMITTED", at: "2026-09-13T08:00:00Z" }],
  },
  {
    id: "6",
    reference: "REQ-10433",
    title: "Statistics tutoring — hypothesis testing",
    category: "tutoring",
    description: "Weekly tutoring on hypothesis testing and confidence intervals ahead of mid-semester exams.",
    course: "ST 201",
    department: "Statistics",
    status: "ASSIGNED",
    priority: "NORMAL",
    deadline: "2026-09-30T15:00:00Z",
    progress: 20,
    assignee: team[1],
    studentName: "Kofi Asare",
    studentId: "ST/2023/0910",
    createdAt: "2026-09-10T16:30:00Z",
    updatedAt: "2026-09-12T11:00:00Z",
    files: [],
    paymentStatus: "PAID",
    deliverables: [],
    history: [
      { status: "SUBMITTED", at: "2026-09-10T16:30:00Z" },
      { status: "PAID", at: "2026-09-11T09:00:00Z" },
      { status: "ASSIGNED", at: "2026-09-12T11:00:00Z" },
    ],
  },
];

export const messages: Message[] = [
  {
    id: "m1",
    requestId: "1",
    authorId: "system",
    authorName: "System",
    body: "Request assigned — Kwame Mensah has been assigned to your request.",
    createdAt: "2026-09-10T08:00:00Z",
    kind: "system",
  },
  {
    id: "m2",
    requestId: "1",
    authorId: "t1",
    authorName: "Kwame Mensah",
    body: "Hi Alex — I've read the brief. Before we touch code, let's agree on the data model. Can you share your current schema?",
    createdAt: "2026-09-10T10:22:00Z",
    kind: "support",
    read: true,
  },
  {
    id: "m3",
    requestId: "1",
    authorId: "s1",
    authorName: "Alex Nyarko",
    body: "Sure, attaching what I have. The departments and courses tables are the part I'm unsure about.",
    createdAt: "2026-09-10T11:05:00Z",
    kind: "student",
    read: true,
    attachment: { name: "schema-v2.sql", size: 12_004 },
  },
  {
    id: "m4",
    requestId: "1",
    authorId: "t1",
    authorName: "Kwame Mensah",
    body: "Good start. I've left review notes in the deliverable — walk through them and tell me which parts feel unclear so we can cover them on the call.",
    createdAt: "2026-09-13T14:05:00Z",
    kind: "support",
    read: false,
  },
  {
    id: "m5",
    requestId: "1",
    authorId: "admin",
    authorName: "Operations",
    body: "Internal: student is close to deadline — prioritise the deployment walkthrough.",
    createdAt: "2026-09-13T14:20:00Z",
    kind: "internal",
  },
  {
    id: "m6",
    requestId: "2",
    authorId: "system",
    authorName: "System",
    body: "Request received and is under review.",
    createdAt: "2026-09-13T07:30:00Z",
    kind: "system",
  },
];

export const resources: Resource[] = [
  {
    id: "r1",
    title: "Exam revision framework",
    description: "A structured six-week revision plan template used by our tutors.",
    category: "Study guides",
    format: "PDF",
    size: "1.2 MB",
    updated: "2026-08-30",
  },
  {
    id: "r2",
    title: "Debugging playbook for students",
    description: "How to read a stack trace, isolate a failure and write a minimal reproduction.",
    category: "Programming resources",
    format: "Guide",
    size: "820 KB",
    updated: "2026-09-02",
  },
  {
    id: "r3",
    title: "Past questions — Data structures",
    description: "Five years of past papers with worked solution outlines.",
    category: "Past questions",
    format: "PDF",
    size: "4.6 MB",
    updated: "2026-07-18",
  },
  {
    id: "r4",
    title: "60 final-year project ideas",
    description: "Scoped project concepts across software, IoT, data and health tech.",
    category: "Project ideas",
    format: "Guide",
    size: "640 KB",
    updated: "2026-09-09",
  },
  {
    id: "r5",
    title: "Research methodology checklist",
    description: "Choose a methodology and justify it defensibly in your proposal.",
    category: "Research resources",
    format: "Template",
    size: "310 KB",
    updated: "2026-08-11",
  },
  {
    id: "r6",
    title: "Technical CV and portfolio guide",
    description: "Turn coursework and projects into a credible graduate portfolio.",
    category: "Career resources",
    format: "Guide",
    size: "980 KB",
    updated: "2026-09-05",
  },
  {
    id: "r7",
    title: "Git workflow starter",
    description: "Branching, commits and collaboration habits for group projects.",
    category: "Programming resources",
    format: "Repo",
    size: "—",
    updated: "2026-06-28",
  },
  {
    id: "r8",
    title: "Referencing quick reference",
    description: "APA, IEEE and Harvard patterns side by side with examples.",
    category: "Study guides",
    format: "PDF",
    size: "420 KB",
    updated: "2026-08-22",
  },
];
