/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AdminAdminRouteImport } from './routes/admin/_admin'
import { Route as AppAppRouteImport } from './routes/app/_app'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesCategoryRouteImport } from './routes/services/$category'
import { Route as AdminAdminIndexRouteImport } from './routes/admin/_admin.index'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/admin/_admin.analytics'
import { Route as AdminAdminMessagesRouteImport } from './routes/admin/_admin.messages'
import { Route as AdminAdminPaymentsRouteImport } from './routes/admin/_admin.payments'
import { Route as AdminAdminResourcesRouteImport } from './routes/admin/_admin.resources'
import { Route as AdminAdminServicesRouteImport } from './routes/admin/_admin.services'
import { Route as AdminAdminSettingsRouteImport } from './routes/admin/_admin.settings'
import { Route as AdminAdminStudentsRouteImport } from './routes/admin/_admin.students'
import { Route as AdminAdminTeamRouteImport } from './routes/admin/_admin.team'
import { Route as AppAppIndexRouteImport } from './routes/app/_app.index'
import { Route as AppAppMessagesRouteImport } from './routes/app/_app.messages'
import { Route as AppAppPaymentsRouteImport } from './routes/app/_app.payments'
import { Route as AppAppProfileRouteImport } from './routes/app/_app.profile'
import { Route as AppAppResourcesRouteImport } from './routes/app/_app.resources'
import { Route as AppAppSettingsRouteImport } from './routes/app/_app.settings'
import { Route as AdminAdminRequestsIndexRouteImport } from './routes/admin/_admin.requests.index'
import { Route as AdminAdminRequestsIdRouteImport } from './routes/admin/_admin.requests.$id'
import { Route as AppAppRequestsIndexRouteImport } from './routes/app/_app.requests.index'
import { Route as AppAppRequestsIdRouteImport } from './routes/app/_app.requests.$id'
import { Route as AppAppRequestsNewRouteImport } from './routes/app/_app.requests.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app/_app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCategoryRoute = ServicesCategoryRouteImport.update({
  id: '/services/$category',
  path: '/services/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMessagesRoute = AdminAdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPaymentsRoute = AdminAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminResourcesRoute = AdminAdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminServicesRoute = AdminAdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminStudentsRoute = AdminAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminTeamRoute = AdminAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppMessagesRoute = AppAppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppPaymentsRoute = AppAppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppProfileRoute = AppAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppResourcesRoute = AppAppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppSettingsRoute = AppAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAppRoute,
} as any)
const AdminAdminRequestsIndexRoute = AdminAdminRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminRequestsIdRoute = AdminAdminRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AppAppRequestsIndexRoute = AppAppRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppRequestsIdRoute = AppAppRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppRequestsNewRoute = AppAppRequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => AppAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/app': typeof AppAppRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/services/$category': typeof ServicesCategoryRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/resources': typeof AdminAdminResourcesRoute
  '/admin/services': typeof AdminAdminServicesRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/students': typeof AdminAdminStudentsRoute
  '/admin/team': typeof AdminAdminTeamRoute
  '/app/messages': typeof AppAppMessagesRoute
  '/app/payments': typeof AppAppPaymentsRoute
  '/app/profile': typeof AppAppProfileRoute
  '/app/resources': typeof AppAppResourcesRoute
  '/app/settings': typeof AppAppSettingsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/app/': typeof AppAppIndexRoute
  '/admin/requests/$id': typeof AdminAdminRequestsIdRoute
  '/app/requests/$id': typeof AppAppRequestsIdRoute
  '/app/requests/new': typeof AppAppRequestsNewRoute
  '/admin/requests/': typeof AdminAdminRequestsIndexRoute
  '/app/requests/': typeof AppAppRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/services/$category': typeof ServicesCategoryRoute
  '/services': typeof ServicesIndexRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/resources': typeof AdminAdminResourcesRoute
  '/admin/services': typeof AdminAdminServicesRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/students': typeof AdminAdminStudentsRoute
  '/admin/team': typeof AdminAdminTeamRoute
  '/app/messages': typeof AppAppMessagesRoute
  '/app/payments': typeof AppAppPaymentsRoute
  '/app/profile': typeof AppAppProfileRoute
  '/app/resources': typeof AppAppResourcesRoute
  '/app/settings': typeof AppAppSettingsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/app': typeof AppAppIndexRoute
  '/admin/requests/$id': typeof AdminAdminRequestsIdRoute
  '/app/requests/$id': typeof AppAppRequestsIdRoute
  '/app/requests/new': typeof AppAppRequestsNewRoute
  '/admin/requests': typeof AdminAdminRequestsIndexRoute
  '/app/requests': typeof AppAppRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/app/_app': typeof AppAppRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/services/$category': typeof ServicesCategoryRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/_admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/_admin/messages': typeof AdminAdminMessagesRoute
  '/admin/_admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/_admin/resources': typeof AdminAdminResourcesRoute
  '/admin/_admin/services': typeof AdminAdminServicesRoute
  '/admin/_admin/settings': typeof AdminAdminSettingsRoute
  '/admin/_admin/students': typeof AdminAdminStudentsRoute
  '/admin/_admin/team': typeof AdminAdminTeamRoute
  '/app/_app/messages': typeof AppAppMessagesRoute
  '/app/_app/payments': typeof AppAppPaymentsRoute
  '/app/_app/profile': typeof AppAppProfileRoute
  '/app/_app/resources': typeof AppAppResourcesRoute
  '/app/_app/settings': typeof AppAppSettingsRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
  '/app/_app/': typeof AppAppIndexRoute
  '/admin/_admin/requests/$id': typeof AdminAdminRequestsIdRoute
  '/app/_app/requests/$id': typeof AppAppRequestsIdRoute
  '/app/_app/requests/new': typeof AppAppRequestsNewRoute
  '/admin/_admin/requests/': typeof AdminAdminRequestsIndexRoute
  '/app/_app/requests/': typeof AppAppRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/how-it-works'
    | '/admin'
    | '/app'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/services/$category'
    | '/services/'
    | '/admin/analytics'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/resources'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/team'
    | '/app/messages'
    | '/app/payments'
    | '/app/profile'
    | '/app/resources'
    | '/app/settings'
    | '/admin/'
    | '/app/'
    | '/admin/requests/$id'
    | '/app/requests/$id'
    | '/app/requests/new'
    | '/admin/requests/'
    | '/app/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/how-it-works'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/services/$category'
    | '/services'
    | '/admin/analytics'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/resources'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/team'
    | '/app/messages'
    | '/app/payments'
    | '/app/profile'
    | '/app/resources'
    | '/app/settings'
    | '/admin'
    | '/app'
    | '/admin/requests/$id'
    | '/app/requests/$id'
    | '/app/requests/new'
    | '/admin/requests'
    | '/app/requests'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/how-it-works'
    | '/admin/_admin'
    | '/app/_app'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/services/$category'
    | '/services/'
    | '/admin/_admin/analytics'
    | '/admin/_admin/messages'
    | '/admin/_admin/payments'
    | '/admin/_admin/resources'
    | '/admin/_admin/services'
    | '/admin/_admin/settings'
    | '/admin/_admin/students'
    | '/admin/_admin/team'
    | '/app/_app/messages'
    | '/app/_app/payments'
    | '/app/_app/profile'
    | '/app/_app/resources'
    | '/app/_app/settings'
    | '/admin/_admin/'
    | '/app/_app/'
    | '/admin/_admin/requests/$id'
    | '/app/_app/requests/$id'
    | '/app/_app/requests/new'
    | '/admin/_admin/requests/'
    | '/app/_app/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  AppAppRoute: typeof AppAppRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ServicesCategoryRoute: typeof ServicesCategoryRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app': {
      id: '/app/_app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$category': {
      id: '/services/$category'
      path: '/services/$category'
      fullPath: '/services/$category'
      preLoaderRoute: typeof ServicesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/analytics': {
      id: '/admin/_admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/messages': {
      id: '/admin/_admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminAdminMessagesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/payments': {
      id: '/admin/_admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminAdminPaymentsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/resources': {
      id: '/admin/_admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminAdminResourcesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/services': {
      id: '/admin/_admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminAdminServicesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/settings': {
      id: '/admin/_admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/students': {
      id: '/admin/_admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminAdminStudentsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/team': {
      id: '/admin/_admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminAdminTeamRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/app/_app/': {
      id: '/app/_app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/messages': {
      id: '/app/_app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppAppMessagesRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/payments': {
      id: '/app/_app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppAppPaymentsRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/profile': {
      id: '/app/_app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppAppProfileRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/resources': {
      id: '/app/_app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AppAppResourcesRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/settings': {
      id: '/app/_app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppAppSettingsRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/admin/_admin/requests/': {
      id: '/admin/_admin/requests/'
      path: '/requests'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AdminAdminRequestsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/requests/$id': {
      id: '/admin/_admin/requests/$id'
      path: '/requests/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AdminAdminRequestsIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/app/_app/requests/': {
      id: '/app/_app/requests/'
      path: '/requests'
      fullPath: '/app/requests/'
      preLoaderRoute: typeof AppAppRequestsIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/requests/$id': {
      id: '/app/_app/requests/$id'
      path: '/requests/$id'
      fullPath: '/app/requests/$id'
      preLoaderRoute: typeof AppAppRequestsIdRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/requests/new': {
      id: '/app/_app/requests/new'
      path: '/requests/new'
      fullPath: '/app/requests/new'
      preLoaderRoute: typeof AppAppRequestsNewRouteImport
      parentRoute: typeof AppAppRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminMessagesRoute: typeof AdminAdminMessagesRoute
  AdminAdminPaymentsRoute: typeof AdminAdminPaymentsRoute
  AdminAdminResourcesRoute: typeof AdminAdminResourcesRoute
  AdminAdminServicesRoute: typeof AdminAdminServicesRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminStudentsRoute: typeof AdminAdminStudentsRoute
  AdminAdminTeamRoute: typeof AdminAdminTeamRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminRequestsIdRoute: typeof AdminAdminRequestsIdRoute
  AdminAdminRequestsIndexRoute: typeof AdminAdminRequestsIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminMessagesRoute: AdminAdminMessagesRoute,
  AdminAdminPaymentsRoute: AdminAdminPaymentsRoute,
  AdminAdminResourcesRoute: AdminAdminResourcesRoute,
  AdminAdminServicesRoute: AdminAdminServicesRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminStudentsRoute: AdminAdminStudentsRoute,
  AdminAdminTeamRoute: AdminAdminTeamRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminRequestsIdRoute: AdminAdminRequestsIdRoute,
  AdminAdminRequestsIndexRoute: AdminAdminRequestsIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AppAppRouteChildren {
  AppAppMessagesRoute: typeof AppAppMessagesRoute
  AppAppPaymentsRoute: typeof AppAppPaymentsRoute
  AppAppProfileRoute: typeof AppAppProfileRoute
  AppAppResourcesRoute: typeof AppAppResourcesRoute
  AppAppSettingsRoute: typeof AppAppSettingsRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppRequestsIdRoute: typeof AppAppRequestsIdRoute
  AppAppRequestsNewRoute: typeof AppAppRequestsNewRoute
  AppAppRequestsIndexRoute: typeof AppAppRequestsIndexRoute
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppMessagesRoute: AppAppMessagesRoute,
  AppAppPaymentsRoute: AppAppPaymentsRoute,
  AppAppProfileRoute: AppAppProfileRoute,
  AppAppResourcesRoute: AppAppResourcesRoute,
  AppAppSettingsRoute: AppAppSettingsRoute,
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppRequestsIdRoute: AppAppRequestsIdRoute,
  AppAppRequestsNewRoute: AppAppRequestsNewRoute,
  AppAppRequestsIndexRoute: AppAppRequestsIndexRoute,
}

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  AdminAdminRoute: AdminAdminRouteWithChildren,
  AppAppRoute: AppAppRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ServicesCategoryRoute: ServicesCategoryRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
